M48
; DRILL file KiCad 10.0.3-10.0.3~ubuntu24.04.1 date 2026-06-23T10:51:49
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-23T10:51:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3-10.0.3~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X178.0Y-45.0
X178.0Y-125.0
X223.0Y-45.0
X223.0Y-125.0
M30
