"""Publish data: public, read-only embeds of a chosen slice of hive data.

The local dashboard is login-protected end to end, which is right for a control
surface but leaves no way to show "how heavy is the hive today" on a club
website, a blog or a shop page. This module adds the missing, explicit step:

1. An admin publishes a chart from the dashboard's **Publish** view — a metric,
   an ordered list of hives, a rolling period and a few presentation options.
2. The server mints an unguessable token and serves exactly that slice, with no
   login, from two public routes:

   * ``GET /embed/chart/{token}``          — a self-contained page to ``<iframe>``
   * ``GET /api/v1/public/charts/{token}`` — the same data as JSON (CORS: ``*``),
     plus ``…/{token}.csv`` for spreadsheets

Everything else stays private. Nothing is public until someone publishes it,
the payload carries resolved display labels rather than device ids, and a
publication is revoked by deleting it (or clearing ``enabled``) — the token is
the capability, so revocation is immediate.

The management API lives under ``/api/v1/local/publish/*`` next to the rest of
the dashboard API: reading the list needs a session, creating/editing/deleting
needs the admin role. The whole feature (public routes included) is gated by
ENABLE_LOCAL_DASHBOARD and ENABLE_PUBLIC_EMBEDS.
"""

import csv
import io
import re
import secrets
import threading
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Optional

import psycopg.types.json
from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, PlainTextResponse

from auth import (
    get_dashboard_user_by_username,
    require_dashboard_admin,
    require_dashboard_session,
)
from config import ENABLE_LOCAL_DASHBOARD, ENABLE_PUBLIC_EMBEDS, PUBLIC_BASE_URL
from db import get_conn
from measurements import (
    CHART_MEASUREMENT_COLUMNS,
    execute_measurement_query,
    serialize_chart_measurements,
)
from schemas import PublishedChartIn, PublishedChartUpdateIn

router = APIRouter()

EMBED_DIR = Path(__file__).resolve().parent / "embed"
DASHBOARD_ASSETS_DIR = Path(__file__).resolve().parent / "dashboard" / "assets"

# Assets the public embed page may load, by exact name. A whitelist rather than a
# StaticFiles mount: charts.js is deliberately served straight out of the
# dashboard's asset directory (the embed draws with the very same chart code, so
# there is no second copy to keep in sync), and an explicit map makes it obvious
# that nothing else from that directory is reachable without a login.
EMBED_ASSETS = {
    "embed.js": EMBED_DIR / "embed.js",
    "embed.css": EMBED_DIR / "embed.css",
    "charts.js": DASHBOARD_ASSETS_DIR / "charts.js",
}

# Tokens are generated by secrets.token_urlsafe; the pattern is enforced on the
# way in as well so a malformed path can never reach a query or a file lookup.
TOKEN_RE = re.compile(r"^[A-Za-z0-9_-]{8,64}$")

# Chart series colours, matching PALETTE in dashboard/assets/charts.js so a
# published chart looks like the one it was published from.
PALETTE = ["#f2a900", "#2563a8", "#2e7d32", "#b00020", "#7b3fb0", "#0f8a8a"]

# How many raw samples a public payload is built from. The measurement query
# thins evenly across the whole period (see execute_measurement_query), so this
# bounds the response size without truncating the period. Daily aggregates ask
# for more, since they collapse to at most one point per day anyway.
PUBLIC_MAX_POINTS = 600
AGGREGATE_MAX_POINTS = 6000

# Public payloads are cached in-process for a minute: an embed on a busy page
# would otherwise run one measurement query per visitor, and hive data that
# arrives every few minutes gains nothing from being a second fresher.
PUBLIC_CACHE_TTL_SECONDS = 60
_public_cache: dict[str, tuple[float, dict]] = {}
_public_cache_lock = threading.Lock()


# ── Metric registry ──────────────────────────────────────────────────────────
# What can be published, and which measurement keys each metric reads. "hive"
# metrics take a hive number and are published per selected hive; "device"
# metrics belong to the collector (ambient sensors, battery, radio) and are
# published once per selected device.
#
# `keys` are candidates in priority order, first non-null wins — the same
# coalescing the dashboard views do, so a published chart matches what the
# publisher saw. `legacy` supplies the pre-multi-hive column for hives 1–2,
# where the firmware's flat stereo microphone schema has no per-hive key.
METRICS: dict[str, dict[str, Any]] = {
    "weight": {
        "label": "Weight",
        "unit": "kg",
        "digits": 2,
        "scope": "hive",
        # Temperature-compensated weight when a coefficient is configured;
        # serialize_chart_measurements falls back to the raw value otherwise.
        "keys": ["scale_{n}_weight_kg_compensated", "scale_{n}_weight_kg"],
    },
    "hive_temp": {
        "label": "Hive temperature",
        "unit": "°C",
        "digits": 1,
        "scope": "hive",
        "keys": ["hive_{n}_temp_c"],
    },
    "hive_humidity": {
        "label": "In-hive humidity",
        "unit": "%",
        "digits": 0,
        "scope": "hive",
        "keys": ["hive_{n}_humidity_percent"],
    },
    "sound_rms": {
        "label": "Sound level (RMS)",
        "unit": "dBFS",
        "digits": 1,
        "scope": "hive",
        "keys": ["mic_{n}_rms_dbfs"],
        "legacy": {1: "mic_left_rms_dbfs", 2: "mic_right_rms_dbfs"},
    },
    "bees_in": {
        "label": "Bees in (per interval)",
        "unit": "",
        "digits": 0,
        "scope": "hive",
        "keys": ["bee_counter_{n}_interval_in"],
    },
    "bees_out": {
        "label": "Bees out (per interval)",
        "unit": "",
        "digits": 0,
        "scope": "hive",
        "keys": ["bee_counter_{n}_interval_out"],
    },
    "ambient_temp": {
        "label": "Ambient temperature",
        "unit": "°C",
        "digits": 1,
        "scope": "device",
        "keys": ["ambient_temp_c"],
    },
    "ambient_humidity": {
        "label": "Ambient humidity",
        "unit": "%",
        "digits": 0,
        "scope": "device",
        "keys": ["ambient_humidity_percent"],
    },
    "battery_soc": {
        "label": "Collector battery",
        "unit": "%",
        "digits": 0,
        "scope": "device",
        "keys": ["battery_soc_percent"],
    },
    "battery_voltage": {
        "label": "Collector battery voltage",
        "unit": "V",
        "digits": 2,
        "scope": "device",
        "keys": ["battery_voltage"],
    },
    "solar_power": {
        "label": "Solar power",
        "unit": "mW",
        "digits": 0,
        "scope": "device",
        "keys": ["solar_power_mw"],
    },
    "rssi": {
        "label": "Signal strength",
        "unit": "dBm",
        "digits": 0,
        "scope": "device",
        "keys": ["rssi_dbm"],
    },
}


def metric_keys(metric: str, hive: Optional[int]) -> list[str]:
    """Measurement keys for ``metric`` on ``hive``, best candidate first.

    Device-level metrics ignore ``hive``. Hive-level metrics substitute the hive
    number into the templated keys and append the legacy flat column for hives
    1–2 where one exists (older rows carry only ``mic_left_*``/``mic_right_*``).
    """
    spec = METRICS[metric]
    if spec["scope"] == "device":
        return list(spec["keys"])
    if hive is None:
        raise ValueError(f"metric '{metric}' is per hive and needs a hive number")
    keys = [k.format(n=hive) for k in spec["keys"]]
    legacy = (spec.get("legacy") or {}).get(hive)
    if legacy:
        keys.append(legacy)
    return keys


def _numeric(value: Any) -> Optional[float]:
    """Coerce a measurement value to a float, or None if it is not a number.

    Postgres NUMERIC columns come back as Decimal, and some values arrive as
    numeric-looking strings out of raw_json; both must plot.
    """
    if value is None or isinstance(value, bool):
        return None
    try:
        out = float(value)
    except (TypeError, ValueError):
        return None
    return out if out == out and out not in (float("inf"), float("-inf")) else None


def series_points(
    measurements: list[dict], keys: list[str], aggregate: str = "none"
) -> list[list]:
    """Build ``[[iso8601, value], …]`` (oldest first) for one published series.

    ``measurements`` is the newest-first list the chart query returns. For each
    row the first non-null key wins, mirroring the dashboard's coalescing.

    ``aggregate`` buckets the points by UTC calendar day: ``daily_max`` /
    ``daily_min`` keep the extreme reading (stamped at the moment it happened,
    as the dashboard's daily-max chart does), ``daily_avg`` averages the day and
    stamps it at midday. Buckets are built from the sampled rows the query
    returned, so on multi-year ranges a daily extreme is a close approximation
    rather than an exhaustive scan.
    """
    raw: list[tuple[datetime, float]] = []
    for m in measurements:
        at = m.get("measured_at")
        if at is None:
            continue
        value = None
        for k in keys:
            if m.get(k) is not None:
                value = _numeric(m[k])
                break
        if value is None:
            continue
        raw.append((at, value))
    raw.sort(key=lambda p: p[0])

    if aggregate == "none" or not raw:
        return [[_iso(at), v] for at, v in raw]

    buckets: dict[Any, list[tuple[datetime, float]]] = {}
    for at, v in raw:
        buckets.setdefault(at.astimezone(timezone.utc).date(), []).append((at, v))

    out: list[list] = []
    for day in sorted(buckets):
        rows = buckets[day]
        if aggregate == "daily_avg":
            mean = sum(v for _, v in rows) / len(rows)
            noon = datetime(day.year, day.month, day.day, 12, tzinfo=timezone.utc)
            out.append([_iso(noon), mean])
            continue
        pick = max(rows, key=lambda p: p[1]) if aggregate == "daily_max" else min(rows, key=lambda p: p[1])
        out.append([_iso(pick[0]), pick[1]])
    return out


def _iso(at: datetime) -> str:
    """UTC ISO-8601 with a trailing Z, which every browser's Date() parses."""
    if at.tzinfo is None:
        at = at.replace(tzinfo=timezone.utc)
    return at.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")


# ── Gates ────────────────────────────────────────────────────────────────────


def require_publishing() -> None:
    """404 unless publishing is switched on, for public and admin routes alike.

    404 rather than 403 for the same reason the rest of the local dashboard API
    masks itself: on a server that does not run this feature, the routes should
    be indistinguishable from routes that do not exist.
    """
    if not (ENABLE_LOCAL_DASHBOARD and ENABLE_PUBLIC_EMBEDS):
        raise HTTPException(status_code=404, detail="Not Found")


PUBLISH_DEP = [Depends(require_publishing), Depends(require_dashboard_session)]
PUBLISH_ADMIN_DEP = [Depends(require_publishing), Depends(require_dashboard_admin)]
PUBLIC_DEP = [Depends(require_publishing)]


# ── Persistence ──────────────────────────────────────────────────────────────

CHART_COLUMNS = """
    id, token, title, subtitle, metric, chart_type, aggregate, series,
    range_days, options, enabled, created_at, updated_at, view_count, last_viewed_at
"""


def _row_to_chart(r) -> dict:
    return {
        "id": r[0],
        "token": r[1],
        "title": r[2],
        "subtitle": r[3],
        "metric": r[4],
        "chart_type": r[5],
        "aggregate": r[6],
        "series": r[7] or [],
        "range_days": r[8],
        "options": r[9] or {},
        "enabled": bool(r[10]),
        "created_at": r[11],
        "updated_at": r[12],
        "view_count": r[13],
        "last_viewed_at": r[14],
    }


def _new_token() -> str:
    return secrets.token_urlsafe(16)


def _validate_metric(metric: str) -> dict:
    spec = METRICS.get(metric)
    if spec is None:
        raise HTTPException(
            status_code=400,
            detail=f"Unknown metric '{metric}'. See GET /api/v1/local/publish/metrics.",
        )
    return spec


def _validate_series(spec: dict, series: list) -> list[dict]:
    """Check the requested series against the metric's scope and the device list.

    A hive metric needs a hive number on every series; a device metric must not
    carry one (publishing "ambient temperature of hive 3" would silently plot the
    whole collector's reading under a hive's name). Unknown devices are rejected
    here rather than becoming an embed that renders empty forever.
    """
    known = _known_device_ids([s.device_id for s in series])
    out: list[dict] = []
    seen: set[tuple[str, Optional[int]]] = set()
    for s in series:
        if s.device_id not in known:
            raise HTTPException(status_code=404, detail=f"Unknown device: {s.device_id}")
        hive = s.hive
        if spec["scope"] == "hive" and hive is None:
            raise HTTPException(
                status_code=400,
                detail="This metric is measured per hive — every series needs a hive number.",
            )
        if spec["scope"] == "device":
            hive = None
        key = (s.device_id, hive)
        if key in seen:
            raise HTTPException(
                status_code=400,
                detail=(
                    "The same device is published twice in this chart."
                    if spec["scope"] == "device"
                    else "The same hive is published twice in this chart."
                ),
            )
        seen.add(key)
        out.append({"device_id": s.device_id, "hive": hive, "label": s.label.strip()})
    return out


def _known_device_ids(candidates: list[str]) -> set[str]:
    if not candidates:
        return set()
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT device_id FROM devices WHERE device_id = ANY(%s);",
                (list(set(candidates)),),
            )
            return {row[0] for row in cur.fetchall()}


def _fetch_chart_by_id(chart_id: int) -> Optional[dict]:
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                f"SELECT {CHART_COLUMNS} FROM published_charts WHERE id = %s;", (chart_id,)
            )
            row = cur.fetchone()
    return _row_to_chart(row) if row else None


def _invalidate_public_cache(token: str) -> None:
    with _public_cache_lock:
        _public_cache.pop(token, None)


# ── Management API (dashboard) ───────────────────────────────────────────────


@router.get("/api/v1/local/publish/metrics", dependencies=PUBLISH_DEP)
def local_publish_metrics():
    """The publishable metrics, so the dashboard never hardcodes the registry."""
    return [
        {
            "id": key,
            "label": spec["label"],
            "unit": spec["unit"],
            "digits": spec["digits"],
            "scope": spec["scope"],
        }
        for key, spec in METRICS.items()
    ]


def _embed_base(request: Request) -> str:
    """Origin the embed URLs are built from.

    PUBLIC_BASE_URL when the operator has configured one (the address the outside
    world reaches this server on, which is what belongs in an embed snippet on
    somebody else's website), otherwise the origin this request arrived on.
    """
    if PUBLIC_BASE_URL:
        return PUBLIC_BASE_URL
    return str(request.base_url).rstrip("/")


def _with_urls(chart: dict, base: str) -> dict:
    """Attach the ready-to-paste URLs for one publication."""
    token = chart["token"]
    return {
        **chart,
        "embed_url": f"{base}/embed/chart/{token}",
        "data_url": f"{base}/api/v1/public/charts/{token}",
        "csv_url": f"{base}/api/v1/public/charts/{token}.csv",
    }


@router.get("/api/v1/local/publish/charts", dependencies=PUBLISH_DEP)
def local_list_published_charts(request: Request):
    """Every publication on this server, newest first."""
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(f"SELECT {CHART_COLUMNS} FROM published_charts ORDER BY created_at DESC;")
            rows = cur.fetchall()
    base = _embed_base(request)
    return [_with_urls(_row_to_chart(r), base) for r in rows]


@router.post("/api/v1/local/publish/charts", dependencies=[Depends(require_publishing)])
def local_create_published_chart(
    body: PublishedChartIn, request: Request, admin: dict = Depends(require_dashboard_admin)
):
    """Publish a chart and mint its public token (admin only).

    The publication is live the moment this returns: the embed URL in the
    response serves the data to anyone who has it. Nothing else on the server
    becomes reachable — the token addresses this slice and only this slice.
    """
    spec = _validate_metric(body.metric)
    series = _validate_series(spec, body.series)
    user = get_dashboard_user_by_username(admin["username"])
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                f"""
                INSERT INTO published_charts
                    (token, title, subtitle, metric, chart_type, aggregate, series,
                     range_days, options, created_by)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING {CHART_COLUMNS};
                """,
                (
                    _new_token(),
                    body.title.strip(),
                    (body.subtitle or "").strip() or None,
                    body.metric,
                    body.chart_type,
                    body.aggregate,
                    psycopg.types.json.Jsonb(series),
                    body.range_days,
                    psycopg.types.json.Jsonb(body.options.model_dump()),
                    user["id"] if user else None,
                ),
            )
            row = cur.fetchone()
            conn.commit()
    return _with_urls(_row_to_chart(row), _embed_base(request))


@router.patch("/api/v1/local/publish/charts/{chart_id}", dependencies=PUBLISH_ADMIN_DEP)
def local_update_published_chart(chart_id: int, body: PublishedChartUpdateIn, request: Request):
    """Edit a publication in place, keeping its token (admin only).

    Editing rather than re-publishing is the point: an embed already pasted into
    a website keeps working while its title, period or series change under it.
    """
    existing = _fetch_chart_by_id(chart_id)
    if existing is None:
        raise HTTPException(status_code=404, detail="Published chart not found")

    sets: list[str] = []
    params: list[Any] = []
    if body.title is not None:
        sets.append("title = %s")
        params.append(body.title.strip())
    if body.subtitle is not None:
        sets.append("subtitle = %s")
        params.append(body.subtitle.strip() or None)
    if body.chart_type is not None:
        sets.append("chart_type = %s")
        params.append(body.chart_type)
    if body.aggregate is not None:
        sets.append("aggregate = %s")
        params.append(body.aggregate)
    if body.range_days is not None:
        sets.append("range_days = %s")
        params.append(body.range_days)
    if body.options is not None:
        sets.append("options = %s")
        params.append(psycopg.types.json.Jsonb(body.options.model_dump()))
    if body.enabled is not None:
        sets.append("enabled = %s")
        params.append(body.enabled)
    if body.series is not None:
        # The metric cannot change (it decides what the series even mean), so the
        # replacement series are validated against the stored one.
        spec = _validate_metric(existing["metric"])
        sets.append("series = %s")
        params.append(psycopg.types.json.Jsonb(_validate_series(spec, body.series)))
    if not sets:
        return _with_urls(existing, _embed_base(request))

    sets.append("updated_at = now()")
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                f"UPDATE published_charts SET {', '.join(sets)} WHERE id = %s "
                f"RETURNING {CHART_COLUMNS};",
                (*params, chart_id),
            )
            row = cur.fetchone()
            conn.commit()
    _invalidate_public_cache(existing["token"])
    return _with_urls(_row_to_chart(row), _embed_base(request))


@router.delete("/api/v1/local/publish/charts/{chart_id}", dependencies=PUBLISH_ADMIN_DEP)
def local_delete_published_chart(chart_id: int):
    """Revoke a publication (admin only). The embed 404s from the next request."""
    existing = _fetch_chart_by_id(chart_id)
    if existing is None:
        raise HTTPException(status_code=404, detail="Published chart not found")
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("DELETE FROM published_charts WHERE id = %s;", (chart_id,))
            conn.commit()
    _invalidate_public_cache(existing["token"])
    return {"status": "deleted", "id": chart_id}


# ── Public API ───────────────────────────────────────────────────────────────


def _load_public_chart(token: str, count_view: bool) -> dict:
    """Fetch an enabled publication by token, optionally counting the view."""
    if not TOKEN_RE.match(token):
        raise HTTPException(status_code=404, detail="Not Found")
    with get_conn() as conn:
        with conn.cursor() as cur:
            if count_view:
                # One statement for the read and the view counter: an embed is
                # fetched once per page view and this keeps that to a single
                # round-trip, while giving the publisher a sign of life.
                cur.execute(
                    f"""
                    UPDATE published_charts
                    SET view_count = view_count + 1, last_viewed_at = now()
                    WHERE token = %s AND enabled
                    RETURNING {CHART_COLUMNS};
                    """,
                    (token,),
                )
                row = cur.fetchone()
                conn.commit()
            else:
                cur.execute(
                    f"SELECT {CHART_COLUMNS} FROM published_charts WHERE token = %s AND enabled;",
                    (token,),
                )
                row = cur.fetchone()
    if row is None:
        raise HTTPException(status_code=404, detail="This chart is not published")
    return _row_to_chart(row)


def _measurements_for(device_ids: list[str], start_at: datetime, max_points: int) -> dict[str, list[dict]]:
    """Chart rows per device over the published period, newest first."""
    out: dict[str, list[dict]] = {}
    with get_conn() as conn:
        with conn.cursor() as cur:
            for device_id in device_ids:
                execute_measurement_query(
                    cur,
                    CHART_MEASUREMENT_COLUMNS,
                    ["device_id = %s", "measured_at >= %s"],
                    [device_id, start_at],
                    max_points,
                    max_points,
                )
                out[device_id] = serialize_chart_measurements(cur)
    return out


def build_public_payload(chart: dict) -> dict:
    """The public representation of a publication: labels, points, nothing else.

    Deliberately free of device ids, hive numbers, firmware versions and every
    other field the private API returns — a published weight curve should not
    also disclose the fleet behind it.
    """
    spec = METRICS.get(chart["metric"])
    if spec is None:
        # A metric removed from the registry after something was published with
        # it. Serve the frame rather than a 500, so the embed degrades visibly.
        raise HTTPException(status_code=410, detail="This chart's metric is no longer available")

    start_at = datetime.now(timezone.utc) - timedelta(days=chart["range_days"])
    aggregate = chart["aggregate"]
    # ~8 samples per day is plenty to pick a daily bucket's extreme, and keeps a
    # short publication from pulling thousands of rows to draw a handful of
    # points. A plain line chart never needs more than the drawn resolution.
    max_points = (
        PUBLIC_MAX_POINTS
        if aggregate == "none"
        else max(PUBLIC_MAX_POINTS, min(AGGREGATE_MAX_POINTS, chart["range_days"] * 8))
    )

    device_ids = list(dict.fromkeys(s["device_id"] for s in chart["series"]))
    per_device = _measurements_for(device_ids, start_at, max_points)

    series_out = []
    newest: Optional[str] = None
    for i, s in enumerate(chart["series"]):
        points = series_points(
            per_device.get(s["device_id"], []),
            metric_keys(chart["metric"], s.get("hive")),
            aggregate,
        )
        latest = points[-1] if points else None
        if latest and (newest is None or latest[0] > newest):
            newest = latest[0]
        series_out.append(
            {
                "label": s["label"],
                "color": PALETTE[i % len(PALETTE)],
                "points": points,
                "latest": None if latest is None else {"at": latest[0], "value": latest[1]},
                # Change across the published period — the number a "how is the
                # colony doing" embed is usually really about.
                "change": None if not points or len(points) < 2 else points[-1][1] - points[0][1],
            }
        )

    options = chart["options"] or {}
    return {
        "title": chart["title"],
        "subtitle": chart["subtitle"],
        "metric": chart["metric"],
        "metric_label": spec["label"],
        "unit": spec["unit"],
        "digits": spec["digits"],
        "chart_type": chart["chart_type"],
        "aggregate": aggregate,
        "range_days": chart["range_days"],
        "theme": options.get("theme", "auto"),
        "height": options.get("height", 320),
        "show_legend": options.get("show_legend", True),
        "show_updated": options.get("show_updated", True),
        "updated_at": newest,
        "generated_at": _iso(datetime.now(timezone.utc)),
        "series": series_out,
    }


def _public_payload_cached(chart: dict) -> dict:
    now = time.monotonic()
    token = chart["token"]
    with _public_cache_lock:
        hit = _public_cache.get(token)
        if hit and now - hit[0] < PUBLIC_CACHE_TTL_SECONDS:
            return hit[1]
    payload = build_public_payload(chart)
    with _public_cache_lock:
        _public_cache[token] = (time.monotonic(), payload)
    return payload


# Public responses are readable from any website's JavaScript (that is the whole
# point of publishing) and may be held briefly by browsers and CDNs. No cookie is
# involved, so the wildcard grants nothing a plain fetch could not already do.
PUBLIC_HEADERS = {
    "Access-Control-Allow-Origin": "*",
    "Cache-Control": "public, max-age=300",
}


@router.get("/api/v1/public/charts/{token}.csv", dependencies=PUBLIC_DEP)
def public_chart_csv(token: str):
    """The published series as CSV, for spreadsheets and static site builds."""
    chart = _load_public_chart(token, count_view=False)
    payload = _public_payload_cached(chart)
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["timestamp", "series", "value", "unit"])
    for s in payload["series"]:
        for at, value in s["points"]:
            writer.writerow([at, s["label"], value, payload["unit"]])
    filename = re.sub(r"[^A-Za-z0-9._-]+", "-", payload["title"]).strip("-").lower() or "chart"
    return PlainTextResponse(
        buf.getvalue(),
        media_type="text/csv; charset=utf-8",
        headers={
            **PUBLIC_HEADERS,
            "Content-Disposition": f'attachment; filename="{filename}.csv"',
        },
    )


@router.get("/api/v1/public/charts/{token}", dependencies=PUBLIC_DEP)
def public_chart_data(token: str):
    """The published slice as JSON: labels, points, units. No device identity."""
    chart = _load_public_chart(token, count_view=True)
    return JSONResponse(_public_payload_cached(chart), headers=PUBLIC_HEADERS)


# ── Public embed page ────────────────────────────────────────────────────────


@router.get("/embed/chart/{token}", dependencies=PUBLIC_DEP, response_class=HTMLResponse)
def public_chart_page(token: str):
    """A self-contained page rendering one publication, made to be iframed.

    The shell carries no data — only the token — and fetches the JSON above, so
    the page is cheap to cache and the data path is the same one a site owner can
    call directly. Deliberately no X-Frame-Options / frame-ancestors restriction:
    being embedded on someone else's page is the feature.
    """
    chart = _load_public_chart(token, count_view=False)
    html = (EMBED_DIR / "embed.html").read_text(encoding="utf-8")
    # The token matched TOKEN_RE (URL-safe base64) and the title is escaped, so
    # neither can break out of the attribute or the <title> element.
    html = html.replace("{{TOKEN}}", chart["token"]).replace(
        "{{TITLE}}", _escape(chart["title"])
    )
    return HTMLResponse(
        html,
        headers={"Cache-Control": "public, max-age=300", "X-Robots-Tag": "noindex"},
    )


@router.get("/embed/assets/{filename}", dependencies=PUBLIC_DEP)
def public_embed_asset(filename: str):
    """Serve one of the whitelisted embed assets (see EMBED_ASSETS)."""
    path = EMBED_ASSETS.get(filename)
    if path is None or not path.is_file():
        raise HTTPException(status_code=404, detail="Not Found")
    media = "text/javascript" if path.suffix == ".js" else "text/css"
    return FileResponse(
        path,
        media_type=f"{media}; charset=utf-8",
        headers={"Cache-Control": "public, max-age=3600"},
    )


def _escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
